import 'package:flutter/material.dart';
import 'game_icon.dart';
import 'sprite_sheet.dart';

typedef GameArtCell = ({String sheet, int index});

List<Rect>? gameArtRegions(String sheet) {
  // Independently fitted bounds keep tall toys and wide boards intact.
  return switch (sheet) {
    'dreams-a' => const [
        Rect.fromLTRB(41, 169, 323, 441),
        Rect.fromLTRB(351, 180, 628, 428),
        Rect.fromLTRB(646, 111, 912, 440),
        Rect.fromLTRB(968, 135, 1223, 448),
        Rect.fromLTRB(31, 491, 300, 802),
        Rect.fromLTRB(309, 510, 642, 779),
        Rect.fromLTRB(651, 512, 912, 798),
        Rect.fromLTRB(938, 487, 1221, 801),
        Rect.fromLTRB(34, 831, 322, 1156),
        Rect.fromLTRB(352, 840, 619, 1146),
        Rect.fromLTRB(677, 856, 895, 1141),
        Rect.fromLTRB(935, 899, 1233, 1157),
      ],
    'dreams-b' => const [
        Rect.fromLTRB(30, 86, 328, 437),
        Rect.fromLTRB(321, 183, 616, 432),
        Rect.fromLTRB(631, 118, 938, 419),
        Rect.fromLTRB(949, 192, 1231, 412),
        Rect.fromLTRB(24, 520, 310, 802),
        Rect.fromLTRB(330, 550, 619, 789),
        Rect.fromLTRB(666, 486, 913, 805),
        Rect.fromLTRB(942, 539, 1232, 813),
        Rect.fromLTRB(25, 827, 309, 1192),
        Rect.fromLTRB(331, 965, 621, 1166),
        Rect.fromLTRB(645, 903, 918, 1180),
        Rect.fromLTRB(979, 857, 1222, 1200),
      ],
    'actions' => const [
        Rect.fromLTRB(74, 62, 344, 325),
        Rect.fromLTRB(459, 40, 688, 324),
        Rect.fromLTRB(794, 84, 1114, 322),
        Rect.fromLTRB(1142, 85, 1477, 321),
        Rect.fromLTRB(38, 437, 414, 597),
        Rect.fromLTRB(473, 359, 728, 642),
        Rect.fromLTRB(778, 376, 1114, 640),
        Rect.fromLTRB(1172, 348, 1475, 653),
        Rect.fromLTRB(61, 657, 341, 951),
        Rect.fromLTRB(395, 710, 757, 934),
        Rect.fromLTRB(791, 688, 1128, 950),
        Rect.fromLTRB(1176, 719, 1479, 933),
      ],
    'care' => const [
        Rect.fromLTRB(66, 45, 356, 319),
        Rect.fromLTRB(408, 61, 740, 313),
        Rect.fromLTRB(788, 63, 1091, 334),
        Rect.fromLTRB(1165, 60, 1488, 330),
        Rect.fromLTRB(38, 349, 367, 625),
        Rect.fromLTRB(448, 361, 711, 629),
        Rect.fromLTRB(855, 369, 1041, 624),
        Rect.fromLTRB(1221, 371, 1418, 629),
        Rect.fromLTRB(59, 686, 356, 942),
        Rect.fromLTRB(431, 673, 734, 952),
        Rect.fromLTRB(801, 662, 1098, 943),
        Rect.fromLTRB(1164, 697, 1467, 945),
      ],
    'essentials' => const [
        Rect.fromLTRB(81, 47, 381, 344),
        Rect.fromLTRB(435, 60, 721, 334),
        Rect.fromLTRB(771, 53, 1094, 336),
        Rect.fromLTRB(1166, 47, 1412, 346),
        Rect.fromLTRB(61, 366, 382, 676),
        Rect.fromLTRB(452, 361, 702, 673),
        Rect.fromLTRB(793, 373, 1076, 666),
        Rect.fromLTRB(1137, 397, 1452, 672),
        Rect.fromLTRB(82, 698, 347, 951),
        Rect.fromLTRB(452, 695, 703, 959),
        Rect.fromLTRB(824, 693, 1042, 958),
        Rect.fromLTRB(1163, 702, 1444, 957),
      ],
    'food' => const [
        Rect.fromLTRB(64, 34, 345, 324),
        Rect.fromLTRB(412, 61, 692, 323),
        Rect.fromLTRB(756, 80, 1105, 327),
        Rect.fromLTRB(1158, 22, 1499, 330),
        Rect.fromLTRB(36, 364, 384, 652),
        Rect.fromLTRB(469, 350, 665, 646),
        Rect.fromLTRB(761, 388, 1131, 630),
        Rect.fromLTRB(1241, 334, 1439, 668),
        Rect.fromLTRB(37, 701, 384, 925),
        Rect.fromLTRB(437, 674, 739, 947),
        Rect.fromLTRB(838, 631, 1053, 962),
        Rect.fromLTRB(1183, 649, 1485, 965),
      ],
    'friends' => const [
        Rect.fromLTRB(49, 39, 348, 352),
        Rect.fromLTRB(410, 80, 733, 341),
        Rect.fromLTRB(787, 82, 1102, 343),
        Rect.fromLTRB(1138, 57, 1500, 344),
        Rect.fromLTRB(41, 392, 356, 631),
        Rect.fromLTRB(411, 382, 729, 635),
        Rect.fromLTRB(774, 379, 1096, 636),
        Rect.fromLTRB(1122, 403, 1506, 636),
        Rect.fromLTRB(33, 660, 367, 937),
        Rect.fromLTRB(425, 668, 717, 943),
        Rect.fromLTRB(796, 662, 1089, 956),
        Rect.fromLTRB(1167, 662, 1463, 948),
      ],
    'learning' => const [
        Rect.fromLTRB(65, 68, 364, 349),
        Rect.fromLTRB(439, 64, 717, 337),
        Rect.fromLTRB(785, 79, 1071, 342),
        Rect.fromLTRB(1131, 95, 1492, 335),
        Rect.fromLTRB(71, 379, 347, 644),
        Rect.fromLTRB(427, 382, 707, 631),
        Rect.fromLTRB(788, 378, 1086, 633),
        Rect.fromLTRB(1147, 370, 1475, 638),
        Rect.fromLTRB(57, 681, 362, 943),
        Rect.fromLTRB(451, 659, 733, 943),
        Rect.fromLTRB(806, 662, 1059, 942),
        Rect.fromLTRB(1213, 657, 1413, 945),
      ],
    'signals' => const [
        Rect.fromLTRB(70, 88, 386, 330),
        Rect.fromLTRB(450, 44, 744, 336),
        Rect.fromLTRB(816, 64, 1054, 324),
        Rect.fromLTRB(1158, 73, 1474, 330),
        Rect.fromLTRB(62, 368, 405, 633),
        Rect.fromLTRB(456, 384, 742, 633),
        Rect.fromLTRB(854, 371, 1046, 636),
        Rect.fromLTRB(1198, 366, 1448, 649),
        Rect.fromLTRB(112, 689, 341, 962),
        Rect.fromLTRB(446, 705, 744, 945),
        Rect.fromLTRB(817, 677, 1088, 955),
        Rect.fromLTRB(1183, 694, 1471, 957),
      ],
    'world' => const [
        Rect.fromLTRB(76, 44, 376, 338),
        Rect.fromLTRB(430, 92, 741, 307),
        Rect.fromLTRB(816, 85, 1110, 353),
        Rect.fromLTRB(1222, 75, 1462, 329),
        Rect.fromLTRB(77, 358, 363, 634),
        Rect.fromLTRB(450, 359, 694, 628),
        Rect.fromLTRB(782, 404, 1117, 629),
        Rect.fromLTRB(1206, 382, 1465, 637),
        Rect.fromLTRB(73, 663, 365, 945),
        Rect.fromLTRB(480, 663, 669, 949),
        Rect.fromLTRB(780, 716, 1093, 921),
        Rect.fromLTRB(1170, 689, 1476, 937),
      ],
    _ => null,
  };
}

int gameArtColumns(String sheet) => sheet.contains('-solo-') ? 1 : 4;
int gameArtRows(String sheet) => sheet.contains('-solo-') ? 1 : 3;

Future<SpriteSheet> loadGameArtSheet(String sheet) => SpriteSheet.load(
    'assets/images/game/$sheet.png', gameArtColumns(sheet), gameArtRows(sheet),
    regions: gameArtRegions(sheet));

/// Stable atlas addresses shared by inline icons, catalogues and story scenes.
const gameArtCells = <String, GameArtCell>{
  'constructor': (sheet: 'dreams-a', index: 0),
  'slime_kit': (sheet: 'dreams-a', index: 1),
  'giant_plush': (sheet: 'dreams-a', index: 2),
  'scooter': (sheet: 'dreams-a', index: 3),
  'roller_skates': (sheet: 'dreams-a', index: 4),
  'board_game': (sheet: 'dreams-a', index: 5),
  'smartwatch': (sheet: 'dreams-a', index: 6),
  'headphones': (sheet: 'dreams-a', index: 7),
  'science_kit': (sheet: 'dreams-a', index: 8),
  'instant_camera': (sheet: 'dreams-a', index: 9),
  'karaoke': (sheet: 'dreams-a', index: 10),
  'skateboard': (sheet: 'dreams-a', index: 11),
  'robot_kit': (sheet: 'dreams-solo-robot', index: 0),
  'keyboard': (sheet: 'dreams-solo-keyboard', index: 0),
  'tent': (sheet: 'dreams-b', index: 2),
  'game_console': (sheet: 'dreams-b', index: 3),
  'bike': (sheet: 'dreams-b', index: 4),
  'drawing_tablet': (sheet: 'dreams-b', index: 5),
  'telescope': (sheet: 'dreams-b', index: 6),
  'ball_rope': (sheet: 'dreams-b', index: 7),
  'treehouse': (sheet: 'dreams-b', index: 8),
  'trampoline': (sheet: 'dreams-b', index: 9),
  'crayons': (sheet: 'dreams-b', index: 10),
  'kite': (sheet: 'dreams-b', index: 11),
  'gift': (sheet: 'essentials', index: 0),
  'star': (sheet: 'essentials', index: 1),
  'trophy': (sheet: 'essentials', index: 2),
  'medal': (sheet: 'essentials', index: 3),
  'bulb': (sheet: 'essentials', index: 4),
  'plan': (sheet: 'essentials', index: 5),
  'calendar': (sheet: 'essentials', index: 6),
  'wallet': (sheet: 'essentials', index: 7),
  'receipt': (sheet: 'essentials', index: 8),
  'shield': (sheet: 'essentials', index: 9),
  'lock': (sheet: 'essentials', index: 10),
  'key': (sheet: 'essentials', index: 11),
  'dice': (sheet: 'learning', index: 0),
  'puzzle': (sheet: 'learning', index: 1),
  'target': (sheet: 'learning', index: 2),
  'book': (sheet: 'learning', index: 3),
  'notebook': (sheet: 'learning', index: 4),
  'pencil': (sheet: 'learning', index: 5),
  'cart': (sheet: 'learning', index: 6),
  'bags': (sheet: 'learning', index: 7),
  'tag': (sheet: 'learning', index: 8),
  'search': (sheet: 'learning', index: 9),
  'clock': (sheet: 'learning', index: 10),
  'hourglass': (sheet: 'learning', index: 11),
  'apple': (sheet: 'food', index: 0),
  'cookie': (sheet: 'food', index: 1),
  'porridge': (sheet: 'food', index: 2),
  'lunchbox': (sheet: 'food', index: 3),
  'sandwich': (sheet: 'food', index: 4),
  'milk': (sheet: 'food', index: 5),
  'bread': (sheet: 'food', index: 6),
  'icecream': (sheet: 'food-solo-icecream', index: 0),
  'candy': (sheet: 'food', index: 8),
  'lemon': (sheet: 'food', index: 9),
  'juice': (sheet: 'food', index: 10),
  'cake': (sheet: 'food-solo-cake', index: 0),
  'toothbrush': (sheet: 'care', index: 0),
  'basket': (sheet: 'care', index: 1),
  'socks': (sheet: 'care', index: 2),
  'mittens': (sheet: 'care', index: 3),
  'jacket': (sheet: 'care', index: 4),
  'honey': (sheet: 'care', index: 5),
  'medicine': (sheet: 'care', index: 6),
  'water': (sheet: 'care', index: 7),
  'heart': (sheet: 'care', index: 8),
  'seedling': (sheet: 'care', index: 9),
  'flower': (sheet: 'care', index: 10),
  'leaf': (sheet: 'care', index: 11),
  'sun': (sheet: 'world', index: 0),
  'cloud': (sheet: 'world', index: 1),
  'rain': (sheet: 'world', index: 2),
  'moon': (sheet: 'world', index: 3),
  'umbrella': (sheet: 'world', index: 4),
  'rocket': (sheet: 'world', index: 5),
  'planet': (sheet: 'world', index: 6),
  'globe': (sheet: 'world', index: 7),
  'bank': (sheet: 'world', index: 8),
  'phone': (sheet: 'world', index: 9),
  'card': (sheet: 'world', index: 10),
  'tools': (sheet: 'world', index: 11),
  'bunny': (sheet: 'friends', index: 0),
  'bear': (sheet: 'friends', index: 1),
  'cat': (sheet: 'friends', index: 2),
  'hedgehog': (sheet: 'friends', index: 3),
  'frog': (sheet: 'friends', index: 4),
  'owl': (sheet: 'friends', index: 5),
  'panda': (sheet: 'friends', index: 6),
  'puppy': (sheet: 'friends', index: 7),
  'fox': (sheet: 'friends', index: 8),
  'happy': (sheet: 'friends', index: 9),
  'thinking': (sheet: 'friends', index: 10),
  'sad': (sheet: 'friends', index: 11),
  'ball': (sheet: 'actions', index: 0),
  'balloon': (sheet: 'actions', index: 1),
  'bow': (sheet: 'actions', index: 2),
  'cap': (sheet: 'actions', index: 3),
  'glasses': (sheet: 'actions', index: 4),
  'scarf': (sheet: 'actions', index: 5),
  'shirt': (sheet: 'actions', index: 6),
  'backpack': (sheet: 'actions', index: 7),
  'brush': (sheet: 'actions', index: 8),
  'ticket': (sheet: 'actions', index: 9),
  'megaphone': (sheet: 'actions', index: 10),
  'letter': (sheet: 'actions', index: 11),
  'chat': (sheet: 'signals', index: 0),
  'confetti': (sheet: 'signals', index: 1),
  'thumb': (sheet: 'signals', index: 2),
  'hand': (sheet: 'signals', index: 3),
  'handshake': (sheet: 'signals', index: 4),
  'warning': (sheet: 'signals', index: 5),
  'question': (sheet: 'signals', index: 6),
  'flame': (sheet: 'signals', index: 7),
  'egg': (sheet: 'signals', index: 8),
  'paw': (sheet: 'signals', index: 9),
  'strength': (sheet: 'signals', index: 10),
  'sleep': (sheet: 'signals', index: 11),
};

const gameGlyphAliases = <String, String>{
  '✓': 'check',
  '✔': 'check',
  '✦': 'star',
  '🏪': 'cart',
  '🧱': 'constructor',
  '🫧': 'care-stat',
  '🧸': 'giant_plush',
  '🛼': 'roller_skates',
  '🎲': 'dice',
  '⌚': 'smartwatch',
  '🎧': 'headphones',
  '🔬': 'science_kit',
  '📸': 'instant_camera',
  '🎤': 'karaoke',
  '🛹': 'skateboard',
  '🤖': 'robot_kit',
  '🎹': 'keyboard',
  '⛺': 'tent',
  '🎮': 'game_console',
  '🚲': 'bike',
  '🎨': 'drawing_tablet',
  '🖍️': 'crayons',
  '🪁': 'kite',
  '🎁': 'gift',
  '⭐': 'star',
  '🌟': 'star',
  '✨': 'star',
  '★': 'star',
  '🏆': 'trophy',
  '🏅': 'medal',
  '🥇': 'medal',
  '💡': 'bulb',
  '📋': 'plan',
  '📝': 'plan',
  '📜': 'receipt',
  '📅': 'calendar',
  '👛': 'wallet',
  '💰': 'coin',
  '💸': 'coin',
  '💶': 'coin',
  '🪙': 'coin',
  '🐷': 'pig',
  '🧾': 'receipt',
  '🛡️': 'shield',
  '🦺': 'shield',
  '🔒': 'lock',
  '🔐': 'lock',
  '🔑': 'key',
  '🧩': 'puzzle',
  '🎯': 'target',
  '📖': 'book',
  '📘': 'book',
  '📚': 'book',
  '📓': 'notebook',
  '📒': 'notebook',
  '📰': 'book',
  '✏️': 'pencil',
  '🖊️': 'pencil',
  '🛒': 'cart',
  '🛍️': 'bags',
  '🏷️': 'tag',
  '🔖': 'tag',
  '🔍': 'search',
  '🔎': 'search',
  '⏰': 'clock',
  '⏳': 'hourglass',
  '🍎': 'apple',
  '🍪': 'cookie',
  '🥣': 'porridge',
  '🍲': 'food-stat',
  '🍗': 'food-stat',
  '🦴': 'food-stat',
  '🍱': 'lunchbox',
  '🥪': 'sandwich',
  '🥗': 'lunchbox',
  '🥛': 'milk',
  '🍞': 'bread',
  '🍦': 'icecream',
  '🍬': 'candy',
  '🍭': 'candy',
  '🍫': 'cookie',
  '🍋': 'lemon',
  '🧃': 'juice',
  '🎂': 'cake',
  '🥧': 'cake',
  '🍕': 'lunchbox',
  '🪥': 'toothbrush',
  '🧺': 'basket',
  '🧦': 'socks',
  '🧤': 'mittens',
  '🧥': 'jacket',
  '🥻': 'jacket',
  '🍯': 'honey',
  '💊': 'medicine',
  '🩺': 'medicine',
  '🩹': 'medicine',
  '💧': 'water',
  '💛': 'heart',
  '🤍': 'heart',
  '🌱': 'seedling',
  '🌷': 'flower',
  '🌼': 'flower',
  '🍃': 'leaf',
  '🌴': 'leaf',
  '🌵': 'seedling',
  '🧼': 'care-stat',
  '☀️': 'sun',
  '🌞': 'sun',
  '🌅': 'sun',
  '☁️': 'cloud',
  '⛅': 'cloud',
  '🌤️': 'cloud',
  '🌧️': 'rain',
  '🌙': 'moon',
  '☂️': 'umbrella',
  '🚀': 'rocket',
  '🪐': 'planet',
  '🌐': 'globe',
  '🏦': 'bank',
  '🏛️': 'bank',
  '📲': 'phone',
  '📵': 'phone',
  '💳': 'card',
  '🧰': 'tools',
  '🛠️': 'tools',
  '🔨': 'tools',
  '🐰': 'bunny',
  '🐻': 'bear',
  '🐱': 'cat',
  '🦔': 'hedgehog',
  '🐸': 'frog',
  '🦉': 'owl',
  '🐼': 'panda',
  '🐶': 'puppy',
  '🦊': 'fox',
  '😊': 'happy',
  '🙂': 'happy',
  '🤗': 'happy',
  '🤔': 'thinking',
  '🧐': 'thinking',
  '😕': 'sad',
  '😢': 'sad',
  '🤧': 'sad',
  '😴': 'sleep',
  '⚽': 'ball',
  '🎈': 'balloon',
  '🎀': 'bow',
  '🎩': 'cap',
  '👓': 'glasses',
  '🧣': 'scarf',
  '👕': 'shirt',
  '🎒': 'backpack',
  '🖌️': 'brush',
  '🎫': 'ticket',
  '📢': 'megaphone',
  '📣': 'megaphone',
  '✉️': 'letter',
  '💌': 'letter',
  '💼': 'backpack',
  '👟': 'roller_skates',
  '🥾': 'socks',
  '💬': 'chat',
  '💭': 'chat',
  '🎉': 'confetti',
  '👍': 'thumb',
  '✋': 'hand',
  '👋': 'hand',
  '🤝': 'handshake',
  '🤲': 'handshake',
  '⚠️': 'warning',
  '❓': 'question',
  '🔥': 'flame',
  '🥚': 'egg',
  '🐾': 'paw',
  '💪': 'strength',
  '🏋️': 'strength',
  '🏠': 'cozy-stat',
  '🛋️': 'cozy-stat',
  '🛏️': 'sleep',
  '🪑': 'cozy-stat',
  '🖼️': 'drawing_tablet',
  '🐠': 'water',
  '🕯️': 'bulb',
  '🎓': 'book',
  '🚗': 'scooter',
  '🪀': 'ball',
  '🎬': 'ticket',
  '🎠': 'ball_rope',
  '🎪': 'tent',
  '🗺️': 'plan',
  '🧭': 'target',
  '🧮': 'plan',
  '📊': 'plan',
  '📈': 'plan',
  '📉': 'plan',
  '🗂️': 'notebook',
  '🪧': 'tag',
  '🎶': 'keyboard',
  '🧊': 'water',
  '❄️': 'water',
  '🦹': 'shield',
  '🕵️': 'search',
  '🙋': 'hand',
  '🙅': 'hand',
  '🙈': 'lock',
  '🤫': 'lock',
  '😈': 'warning',
  '👵': 'handshake',
  '🚶': 'roller_skates',
  '🚪': 'cozy-stat',
  '🎰': 'warning',
  '🃏': 'board_game',
  '✅': 'check',
  '❌': 'close',
  '🚫': 'block',
  '⛔': 'block',
  '➕': 'plus',
  '➖': 'minus',
  '➡️': 'right',
  '⬆️': 'up',
  '🔙': 'back',
  '🔄': 'refresh',
  '▶️': 'play',
  '👆': 'up',
  '👇': 'down',
  '🚩': 'flag',
  '🏁': 'finish',
  '🔢': 'numbers',
  '🔗': 'link',
  '🆓': 'free',
  '🅰️': 'a',
  '🅱️': 'b',
  '🔹': 'diamond',
  '⬜': 'square',
  '⚖️': 'balance',
  '⚡': 'bolt',
  '🗑️': 'trash',
};

const gameControlIcons = <String, IconData>{
  'check': Icons.check_rounded,
  'close': Icons.close_rounded,
  'block': Icons.block_rounded,
  'plus': Icons.add_rounded,
  'minus': Icons.remove_rounded,
  'right': Icons.arrow_forward_rounded,
  'up': Icons.arrow_upward_rounded,
  'down': Icons.arrow_downward_rounded,
  'back': Icons.arrow_back_rounded,
  'refresh': Icons.refresh_rounded,
  'play': Icons.play_arrow_rounded,
  'flag': Icons.flag_rounded,
  'finish': Icons.sports_score_rounded,
  'numbers': Icons.pin_rounded,
  'link': Icons.link_rounded,
  'free': Icons.redeem_rounded,
  'a': Icons.looks_one_rounded,
  'b': Icons.looks_two_rounded,
  'diamond': Icons.diamond_rounded,
  'square': Icons.crop_square_rounded,
  'balance': Icons.balance_rounded,
  'bolt': Icons.bolt_rounded,
  'trash': Icons.delete_outline_rounded,
};

const _hud = <String, GameIconKind>{
  'coin': GameIconKind.coin,
  'pig': GameIconKind.pig,
  'food-stat': GameIconKind.food,
  'care-stat': GameIconKind.care,
  'cozy-stat': GameIconKind.cozy,
};

String gameArtId(String value) =>
    gameGlyphAliases[value] ??
    gameGlyphAliases['${value.replaceAll('\uFE0F', '')}\uFE0F'] ??
    value;

bool hasGameArt(String value) {
  final id = gameArtId(value);
  return gameArtCells.containsKey(id) ||
      gameControlIcons.containsKey(id) ||
      _hud.containsKey(id);
}

class GameGlyph extends StatelessWidget {
  const GameGlyph(this.id, {super.key, this.size = 24, this.color});
  final String id;
  final double size;
  final Color? color;

  @override
  Widget build(BuildContext context) {
    final key = gameArtId(id);
    if (key == 'a' || key == 'b') {
      return ExcludeSemantics(
          child: Container(
        width: size,
        height: size,
        alignment: Alignment.center,
        decoration: BoxDecoration(
          color: const Color(0xFFE5EEDC),
          borderRadius: BorderRadius.circular(size * .25),
        ),
        child: Text(key.toUpperCase(),
            textScaler: TextScaler.noScaling,
            style: TextStyle(
                fontSize: size * .65,
                fontWeight: FontWeight.w900,
                color: color ?? const Color(0xFF49866F),
                height: 1)),
      ));
    }
    final hud = _hud[key];
    final control = gameControlIcons[key];
    final cell = gameArtCells[key] ?? gameArtCells['question']!;
    return ExcludeSemantics(
      child: SizedBox.square(
        dimension: size,
        child: hud != null
            ? GameIcon(hud, size: size)
            : control != null
                ? Icon(control,
                    size: size, color: color ?? const Color(0xFF49866F))
                : SheetArt(
                    path: 'assets/images/game/${cell.sheet}.png',
                    cell: cell.index,
                    columns: gameArtColumns(cell.sheet),
                    rows: gameArtRows(cell.sheet),
                    regions: gameArtRegions(cell.sheet)),
      ),
    );
  }
}

final gameGlyphPattern = RegExp(
  '${(gameGlyphAliases.keys.toList()..sort((a, b) => b.length.compareTo(a.length))).map(RegExp.escape).join('|')}|[\\u{1F000}-\\u{1FAFF}\\u{2600}-\\u{27BF}]\\uFE0F?',
  unicode: true,
);
